"""empty message

Revision ID: 361d445203ed
Revises: d0530e6c8694
Create Date: 2017-08-29 11:20:10.164274

"""

# revision identifiers, used by Alembic.
revision = '361d445203ed'
down_revision = 'd0530e6c8694'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('target_id', sa.Integer(), nullable=True))
    op.add_column('archives', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_constraint(u'archives_ibfk_2', 'archives', type_='foreignkey')
    op.create_foreign_key(None, 'archives', 'users', ['target_id'], ['id'])
    op.drop_column('archives', 'object_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('object_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'archives', type_='foreignkey')
    op.create_foreign_key(u'archives_ibfk_2', 'archives', 'users', ['object_id'], ['id'])
    op.drop_column('archives', 'title')
    op.drop_column('archives', 'target_id')
    ### end Alembic commands ###
