"""empty message

Revision ID: 494d1ac67e6d
Revises: None
Create Date: 2017-06-13 17:12:32.407347

"""

# revision identifiers, used by Alembic.
revision = '494d1ac67e6d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', table_name='roles')
    op.add_column('survey_metas', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey_metas', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_metas', type_='foreignkey')
    op.drop_column('survey_metas', 'author_id')
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###
