"""empty message

Revision ID: 4ea28477a700
Revises: 494d1ac67e6d
Create Date: 2017-06-16 10:04:59.002365

"""

# revision identifiers, used by Alembic.
revision = '4ea28477a700'
down_revision = '494d1ac67e6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('dimension', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'dimension')
    op.drop_column('surveys', 'content')
    ### end Alembic commands ###
