"""empty message

Revision ID: 500978cd99d3
Revises: 4ea28477a700
Create Date: 2017-06-16 10:12:25.765499

"""

# revision identifiers, used by Alembic.
revision = '500978cd99d3'
down_revision = '4ea28477a700'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('content_origin', sa.Text(), nullable=True))
    op.drop_column('surveys', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('surveys', 'content_origin')
    ### end Alembic commands ###
