"""empty message

Revision ID: 870822432f9e
Revises: 361d445203ed
Create Date: 2017-08-30 14:18:47.510360

"""

# revision identifiers, used by Alembic.
revision = '870822432f9e'
down_revision = '361d445203ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('serial_num', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_serial_num'), 'messages', ['serial_num'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_serial_num'), table_name='messages')
    op.drop_column('messages', 'serial_num')
    ### end Alembic commands ###
