"""empty message

Revision ID: 9799dd6d5573
Revises: 96318282e2f6
Create Date: 2017-06-16 15:02:52.107038

"""

# revision identifiers, used by Alembic.
revision = '9799dd6d5573'
down_revision = '96318282e2f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_id')
    ### end Alembic commands ###
