"""empty message

Revision ID: a5641699d45f
Revises: 870822432f9e
Create Date: 2017-08-31 11:16:21.495842

"""

# revision identifiers, used by Alembic.
revision = 'a5641699d45f'
down_revision = '870822432f9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('root_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['root_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'root_id')
    ### end Alembic commands ###
