"""empty message

Revision ID: c6170594b21e
Revises: 9799dd6d5573
Create Date: 2017-06-16 15:53:29.902580

"""

# revision identifiers, used by Alembic.
revision = 'c6170594b21e'
down_revision = '9799dd6d5573'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.SmallInteger(), nullable=True))
    op.add_column('messages', sa.Column('type', sa.String(length=64), nullable=True))
    op.drop_constraint(u'messages_ibfk_2', 'messages', type_='foreignkey')
    op.drop_column('messages', 'root_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('root_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'messages_ibfk_2', 'messages', 'messages', ['root_id'], ['id'])
    op.drop_column('messages', 'type')
    op.drop_column('messages', 'is_read')
    ### end Alembic commands ###
