"""empty message

Revision ID: d0530e6c8694
Revises: b652b688d0ed
Create Date: 2017-06-22 12:45:09.782925

"""

# revision identifiers, used by Alembic.
revision = 'd0530e6c8694'
down_revision = 'b652b688d0ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_deled', sa.SmallInteger(), nullable=True))
    op.add_column('messages', sa.Column('sender_deled', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_deled')
    op.drop_column('messages', 'receiver_deled')
    ### end Alembic commands ###
